version: '3'

services:
  postgis:
    image: postgis/postgis
    container_name: gis-postgis
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    restart: unless-stopped